name: Feature Request
description: Suggestion of ideas that you believe would be excellent additions to Assorion Engine.
labels: ["Feature's"]
body:
  - type: markdown
    id: statement
    value: |
        Your Feature Request Must Comply with Assorion Engine's guiding principles and foundation.

  - type: textarea
    id: feature
    attributes:
      label: "Which feature would you desire to see implemented?" 
      value: "Information about the requested feature and how it would happen."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Addition Info" 
      value: "Feature Concepts, Images/Screenshots, References, etc."
    validations:
      required: false
