name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
        
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install flixel 5.0.0 
          haxelib install flixel-addons
          haxelib install flixel-ui

      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compilation
        run: haxelib run lime build project.xml linux

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4

        with:
          name: Linux Build
          path: 'export/release/linux/bin'

  buildWindows:
    runs-on: windows-latest
    steps:  
      - uses: actions/checkout@v2.3.0
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install flixel 5.0.0 
          haxelib install flixel-addons
          haxelib install flixel-ui
        shell: cmd
        
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION
        
      - name: Compilation
        run: haxelib run lime build windows
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        
        with:
          name: Windows Build
          path: export/release/windows/bin
