name: HTML5 (Web Builds)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  HTML5-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
        
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime
          haxelib install openfl
          haxelib install flixel 5.0.0 
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2

      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compilation
        run: haxelib run lime build html5 -release

      - name: Tar.gz Compression 
        run: tar -czf Linux-Build.tar.gz 'export/release/linux/bin'
        shell: bash
  
      - name: Upload Artifact
        uses: alehechka/upload-tartifact@main
        with:
          name: Linux-Build
          path: Linux-Build.tar.gz

  Build-Download: 
    name: Build-Download
    runs-on: ubuntu-latest
    needs: HTML5-Build
    steps:
    - name: Download Artifact 
      uses: aalehechka/download-tartifact@main
      with: 
        name: HTML5-Build
    
    - name: Artifact Download
      run: ls -R
