name: HTML5 (Web Builds)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  HTML5-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2

      - name: Caching dependencies
        id: HaxeCache
        uses: actions/cache@main
        with:
          path: /opt/hostedtoolcache/haxe/4.3.2/x64/std/lib
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/opt/hostedtoolcache/haxe/4.3.2/x64/std/lib') }}
        
      - name: Install Haxelib
        if: steps.HaxeCache.outputs.cache-hit != 'true'
        run: |
          echo $HAXE_STD_PATH
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime 7.9.0
          haxelib install openfl 9.2.1
          haxelib install flixel 5.2.2 
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compilation
        run: haxelib run lime build html5 -release

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: HTML5-Build
          path: 'export/release/html5/bin'

  Build-Download: 
    name: Build-Download
    runs-on: ubuntu-latest
    needs: HTML5-Build
    steps:
    - name: Download Artifact 
      uses: actions/download-artifact@main
      with: 
        name: HTML5-Build
