name: Linux

on:
  workflow_dispatch:

jobs:
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2
          
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime
          haxelib install openfl
          haxelib install flixel 5.0.0 
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2

      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compilation
        run: haxelib run lime build Project.xml linux -release --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: alehechka/upload-tartifact@v2
        with:
          name: Linux-Build
          path: 'export/release/linux/bin'

  Build-Download: 
    name: Build-Download
    runs-on: ubuntu-latest
    needs: Linux-Build
    steps:
    - name: Download Artifact 
      uses: alehechka/download-tartifact@v2
      with: 
        name: Linux-Build
    
    - name: Artifact Download
      run: ls -R
