name: Windows

# You can setup workflows to run automatically on specific branches.
# Read the HTML workflow to understand that.
on:
  workflow_dispatch:

jobs:
  Win32-MinGW-x64-Build:
    runs-on: windows-latest
    steps:
      # Use the workflow in-built MinGW version.
      - name: Setup MinGW
        run: |
          cd /d C:\
          md MinGW
          copy mingw64 MinGW
        shell: cmd

      # Install Haxe. 4.1.5 since 4.3.2 breaks MinGW
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      
      # Get Haxe libraries. We are using a custom version of HXCPP with some optimizations.
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib git hxcpp https://github.com/Assorion/HXCPP_O3
          haxelib install lime 7.9.0
          haxelib install openfl 9.2.2
          haxelib install flixel 4.9.0 
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.7.0
        shell: cmd

      # Random Github BS as always, just keep this here.
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION
        
      # Tell HXCPP to compile with MinGW.
      - name: Compile 64-Bit Version
        run: haxelib run lime build windows -D HXCPP_MINGW -release --app-version="4.0.0-${{ github.run_id}}"

      # Provide the 64-Bit file for download
      - name: Publish x64 Artifact
        uses: actions/upload-artifact@main
        with:
          name: Win32-MinGW-x64-Build
          path: export/release/windows/bin
